[server]
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[theme]
primaryColor = "#5465FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"